/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Dataiku;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ApplicationTest {
    
}
